export const optionMap: { [key: string]: { value: number; label: string }[] } =
  {
    A: [
      { value: 1, label: "Absorbers" },
      { value: 2, label: "Among Us" },
    ],
    B: [
      { value: 101, label: "Background Mask" },
      { value: 102, label: "Basic" },
      { value: 103, label: "Big" },
      { value: 104, label: "Black Hole" },
      { value: 105, label: "Bubble" },
    ],
    C: [
      // { value: 201, label: "Cards" },
      { value: 201, label: "Chars" },
      // { value: 202, label: "Click Confetti" },
      { value: 202, label: "Click Pause" },
      { value: 203, label: "Collisions Absorb" },
      { value: 204, label: "Collisions Bounce" },
      { value: 205, label: "Collisions Destroy" },
      { value: 206, label: "Color Animation" },
      { value: 207, label: "Curl Noise" },
    ],
    D: [
      { value: 301, label: "Data Images" },
      { value: 302, label: "Delay Color" },
      { value: 303, label: "Delay Opacity" },
      { value: 304, label: "Delay" },
      { value: 305, label: "Delay Size" },
      { value: 306, label: "Delay Stroke Color" },
      { value: 307, label: "Destroy" },
      { value: 308, label: "Disappearing" },
      { value: 309, label: "Div Events" },
    ],
    E: [
      { value: 401, label: "Effect Bubble" },
      { value: 402, label: "Effect Trail" },
      // { value: 403, label: "Emitter Absorber" },
      // { value: 404, label: "Emitter Angled" },
      // { value: 405, label: "Emitter Image Shape" },
      // { value: 406, label: "Emitter Images" },
      { value: 403, label: "Emitter" },
      // { value: 408, label: "Emitter Paths" },
      // { value: 409, label: "Emitter Shapes" },
      // { value: 410, label: "Emitter Spawn Color" },
      // { value: 411, label: "Emitter Text Shape" },
      // { value: 412, label: "Emitter Text Stroke Shape" },
    ],
    F: [
      // { value: 501, label: "Fireworks 2" },
      // { value: 502, label: "Fireworks" },
      { value: 501, label: "Fontawesome" },
      { value: 502, label: "Forward" },
    ],
    G: [
      { value: 601, label: "Gifs" },
      { value: 602, label: "Grab Random Color" },
      { value: 603, label: "Gradients" },
      // { value: 604, label: "Gravity" },
      // { value: 605, label: "Growing" },
    ],
    H: [
      // { value: 701, label: "Hexagon Path" },
      { value: 701, label: "Hollow Knight" },
      // { value: 703, label: "Hyperspace" },
    ],
    I: [
      { value: 801, label: "Image Mask" },
      { value: 802, label: "Images Directions" },
      { value: 803, label: "Images" }, // images has bugs
      // { value: 804, label: "Infection "},
    ],
    J: [],
    K: [],
    L: [
      { value: 1101, label: "Life" },
      { value: 1102, label: "Light Hover" },
      { value: 1103, label: "Link Triangles" },
      { value: 1104, label: "Local Polygon Mask" },
    ],
    M: [
      { value: 1201, label: "Manual" },
      { value: 1202, label: "Motion Disable" },
      { value: 1203, label: "Motion Reduce" },
      { value: 1204, label: "Mouse Attract" },
      { value: 1205, label: "Mouse Bounce" },
      { value: 1206, label: "Mouse Follow" },
      // { value: 1207, label: "Mouse Particle" },
      { value: 1207, label: "Mouse Particle 2" },
      { value: 1208, label: "Mouse Trail" },
      // { value: 1209, label: "Mouse Trail Noise" },
      { value: 1209, label: "Move Angle" },
      { value: 1210, label: "Move Distance" },
      { value: 1211, label: "Move Inside" },
      { value: 1212, label: "Move Outside" },
      // { value: 1214, label: "Multiple Click Emitters" },
      { value: 1213, label: "Multiple Polygon Masks" },
    ],
    N: [
      { value: 1301, label: "NASA" },
      { value: 1302, label: "No Clear" },
      { value: 1303, label: "Noise Planes" },
      { value: 1304, label: "Nyan Cat" },
      { value: 1305, label: "Nyan Cat 2" },
    ],
    O: [{ value: 1401, label: "Orbit" }],
    P: [
      { value: 1501, label: "Parallax" },
      { value: 1502, label: "Path Polygon Mask" },
      { value: 1503, label: "Path Svg" },
      { value: 1504, label: "Path Zig Zag" },
      { value: 1505, label: "Planes" },
      { value: 1506, label: "Plasma" },
      { value: 1507, label: "Poisson" },
      { value: 1508, label: "Polygon Mask" },
      { value: 1509, label: "Polygons" },
      { value: 1510, label: "Pop" },
    ],
    Q: [],
    R: [
      { value: 1701, label: "Random" },
      { value: 1702, label: "React Bubbles" },
      { value: 1703, label: "React Defaults" },
      { value: 1704, label: "React Multiple Images" },
      { value: 1705, label: "React Night Sky" },
      { value: 1706, label: "React Polygon Mask" },
      { value: 1707, label: "React Simple" },
      { value: 1708, label: "React Snow" },
      { value: 1709, label: "Reduce Duplicates" },
      { value: 1710, label: "Repulse" },
      { value: 1711, label: "Repulse Back" },
      { value: 1712, label: "Repulse Circ" },
      { value: 1713, label: "Repulse Cubic" },
      { value: 1714, label: "Repulse Expo" },
      { value: 1715, label: "Repulse Quart" },
      { value: 1716, label: "Repulse Quint" },
      { value: 1717, label: "Repulse Sine" },
      { value: 1718, label: "Responsive" },
      { value: 1719, label: "Ring" },
    ],
    S: [
      // { value: 1801, label: "Sea Anemone" },
      { value: 1801, label: "Shadow" },
      // { value: 1802, label: "Shape Arrow" },
      // { value: 1803, label: "Shape Cog" },
      // { value: 1804, label: "Shape Emoji" },
      { value: 1805, label: "Shape Heart" },
      { value: 1806, label: "Shape Multiline Text" },
      { value: 1807, label: "Shape Options" },
      // { value: 1808, label: "Shape Path" },
      { value: 1809, label: "Shape Rounded Polygon" },
      { value: 1810, label: "Shape Rounded Rect" },
      // { value: 1811, label: "Shape Spiral" },
      { value: 1812, label: "Slow" },
      { value: 1813, label: "Snow" },
      // { value: 1814, label: "Sounds Audio" },
      // { value: 1815, label: "Sounds Loop" },
      // { value: 1816, label: "Sounds Melodies" },
      // { value: 1817, label: "Sounds Melody Loop" },
      // { value: 1818, label: "Sounds Notes" },
      { value: 1819, label: "Speed Decay" },
      { value: 1820, label: "Spin" },
      { value: 1821, label: "Star" },
      { value: 1822, label: "Stroke Animation" },
      { value: 1823, label: "Style" },
      // { value: 1824, label: "Svg Replace" },
    ],
    T: [
      // { value: 1901, label: "Test" },
      { value: 1901, label: "Text Mask" },
      { value: 1902, label: "Text Mask Multiline" },
      { value: 1903, label: "Themes" },
      // { value: 1905, label: "Tilt" },
      // { value: 1906, label: "Trail" },
      { value: 1904, label: "Trail Image" },
      { value: 1905, label: "Triangles" },
      { value: 1906, label: "Twinkle" },
    ],
    U: [],
    V: [
      { value: 2101, label: "Vibrate" },
      { value: 2102, label: "Virus" },
    ],
    W: [
      // { value: 2201, label: "Warp" },
      // { value: 2201, label: "Wobble" },
    ],
    X: [],
    Y: [],
    Z: [{ value: 2501, label: "Z Index" }],
  };

export const letterToNum: { [key: string]: number } = {
  A: 0,
  B: 1,
  C: 2,
  D: 3,
  E: 4,
  F: 5,
  G: 6,
  H: 7,
  I: 8,
  J: 9,
  K: 10,
  L: 11,
  M: 12,
  N: 13,
  O: 14,
  P: 15,
  Q: 16,
  R: 17,
  S: 18,
  T: 19,
  U: 20,
  V: 21,
  W: 22,
  X: 23,
  Y: 24,
  Z: 25,
};

export const getKeyString = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
