import * as AllPages from "../pages/index";

/**
 * Map of all pages
 */
export const PageMap: { [key: string]: JSX.Element } = {
  Absorbers: <AllPages.AbsorbersPage />,
  "Among Us": <AllPages.AmongUsPage />,
  "Background Mask": <AllPages.BackgroundMaskPage />,
  Basic: <AllPages.BasicPage />,
  Big: <AllPages.BigPage />,
  "Black Hole": <AllPages.BlackHolePage />,
  Bubble: <AllPages.BubblePage />,
  Cards: <AllPages.CardsPage />,
  Chars: <AllPages.CharsPage />,
  "Click Confetti": <AllPages.ClickConfettiPage />,
  "Click Pause": <AllPages.ClickPausePage />,
  "Collisions Absorb": <AllPages.CollisionsAbsorbPage />,
  "Collisions Bounce": <AllPages.CollisionsBouncePage />,
  "Collisions Destroy": <AllPages.CollisionsDestroyPage />,
  "Color Animation": <AllPages.ColorAnimationPage />,
  "Curl Noise": <AllPages.CurlNoisePage />,
  "Data Images": <AllPages.DataImagesPage />,
  "Delay Color": <AllPages.DelayColorPage />,
  "Delay Opacity": <AllPages.DelayOpacityPage />,
  Delay: <AllPages.DelayPage />,
  "Delay Size": <AllPages.DelaySizePage />,
  "Delay Stroke Color": <AllPages.DelayStrokeColorPage />,
  Destroy: <AllPages.DestroyPage />,
  Disappearing: <AllPages.DisappearingPage />,
  "Div Events": <AllPages.DivEventsPage />,
  "Effect Bubble": <AllPages.EffectBubblePage />,
  "Effect Trail": <AllPages.EffectTrailPage />,
  "Emitter Absorber": <AllPages.EmitterAbsorberPage />,
  "Emitter Angled": <AllPages.EmitterAngledPage />,
  "Emitter Image Shape": <AllPages.EmitterImageShapePage />,
  "Emitter Images": <AllPages.EmitterImagesPage />,
  Emitter: <AllPages.EmitterPage />,
  "Emitter Paths": <AllPages.EmitterPathsPage />,
  "Emitter Shapes": <AllPages.EmitterShapesPage />,
  "Emitter Spawn Color": <AllPages.EmitterSpawnColorPage />,
  "Emitter Text Shape": <AllPages.EmitterTextShapePage />,
  "Emitter Text Stroke Shape": <AllPages.EmitterTextStrokeShapePage />,
  "Fireworks 2": <AllPages.Fireworks2Page />,
  Fireworks: <AllPages.FireworksPage />,
  Fontawesome: <AllPages.FontawesomePage />,
  Forward: <AllPages.ForwardPage />,
  Gifs: <AllPages.GifsPage />,
  "Grab Random Color": <AllPages.GrabRandomColorPage />,
  Gradients: <AllPages.GradientsPage />,
  Gravity: <AllPages.GravityPage />,
  Growing: <AllPages.GrowingPage />,
  "Hexagon Path": <AllPages.HexagonPathPage />,
  "Hollow Knight": <AllPages.HollowknightPage />,
  Hyperspace: <AllPages.HyperspacePage />,
  "Image Mask": <AllPages.ImageMaskPage />,
  "Images Directions": <AllPages.ImagesDirectionsPage />,
  Images: <AllPages.ImagesPage />,
  Infection: <AllPages.InfectionPage />,
  Life: <AllPages.LifePage />,
  "Light Hover": <AllPages.LightHoverPage />,
  "Link Triangles": <AllPages.LinkTrianglesPage />,
  "Local Polygon Mask": <AllPages.LocalPolygonMaskPage />,
  Manual: <AllPages.ManualPage />,
  "Motion Disable": <AllPages.MotionDisablePage />,
  "Motion Reduce": <AllPages.MotionReducePage />,
  "Mouse Attract": <AllPages.MouseAttractPage />,
  "Mouse Bounce": <AllPages.MouseBouncePage />,
  "Mouse Follow": <AllPages.MouseFollowPage />,
  "Mouse Particle": <AllPages.MouseParticlePage />,
  "Mouse Particle 2": <AllPages.MouseParticle2Page />,
  "Mouse Trail": <AllPages.MouseTrailPage />,
  "Mouse Trail Noise": <AllPages.MouseTrailNoisePage />,
  "Move Angle": <AllPages.MoveAnglePage />,
  "Move Distance": <AllPages.MoveDistancePage />,
  "Move Inside": <AllPages.MoveInsidePage />,
  "Move Outside": <AllPages.MoveOutsidePage />,
  "Multiple Click Emitters": <AllPages.MultipleClickEmittersPage />,
  "Multiple Polygon Masks": <AllPages.MultiplePolygonMasksPage />,
  NASA: <AllPages.NasaPage />,
  "No Clear": <AllPages.NoClearPage />,
  "Noise Planes": <AllPages.NoisePlanesPage />,
  "Nyan Cat": <AllPages.NyancatPage />,
  "Nyan Cat 2": <AllPages.Nyancat2Page />,
  Orbit: <AllPages.OrbitPage />,
  Parallax: <AllPages.ParallaxPage />,
  "Path Polygon Mask": <AllPages.PathPolygonMaskPage />,
  "Path Svg": <AllPages.PathSvgPage />,
  "Path Zig Zag": <AllPages.PathZigZagPage />,
  Planes: <AllPages.PlanesPage />,
  Plasma: <AllPages.PlasmaPage />,
  Poisson: <AllPages.PoissonPage />,
  "Polygon Mask": <AllPages.PolygonMaskPage />,
  Polygons: <AllPages.PolygonsPage />,
  Pop: <AllPages.PopPage />,
  Random: <AllPages.RandomPage />,
  "React Bubbles": <AllPages.ReactBubblesPage />,
  "React Defaults": <AllPages.ReactDefaultsPage />,
  "React Multiple Images": <AllPages.ReactMultipleImagesPage />,
  "React Night Sky": <AllPages.ReactNightSkyPage />,
  "React Polygon Mask": <AllPages.ReactPolygonMaskPage />,
  "React Simple": <AllPages.ReactSimplePage />,
  "React Snow": <AllPages.ReactSnowPage />,
  "Reduce Duplicates": <AllPages.ReduceDuplicatesPage />,
  Repulse: <AllPages.RepulsePage />,
  "Repulse Back": <AllPages.RepulseBackPage />,
  "Repulse Circ": <AllPages.RepulseCircPage />,
  "Repulse Cubic": <AllPages.RepulseCubicPage />,
  "Repulse Expo": <AllPages.RepulseExpoPage />,
  "Repulse Quart": <AllPages.RepulseQuartPage />,
  "Repulse Quint": <AllPages.RepulseQuintPage />,
  "Repulse Sine": <AllPages.RepulseSinePage />,
  Responsive: <AllPages.ResponsivePage />,
  Ring: <AllPages.RingPage />,
  "Sea Anemone": <AllPages.SeaAnemonePage />,
  Shadow: <AllPages.ShadowPage />,
  "Shape Arrow": <AllPages.ShapeArrowPage />,
  "Shape Cog": <AllPages.ShapeCogPage />,
  "Shape Emoji": <AllPages.ShapeEmojiPage />,
  "Shape Heart": <AllPages.ShapeHeartPage />,
  "Shape Multiline Text": <AllPages.ShapeMultilineTextPage />,
  "Shape Options": <AllPages.ShapeOptionsPage />,
  "Shape Path": <AllPages.ShapePathPage />,
  "Shape Rounded Polygon": <AllPages.ShapeRoundedPolygonPage />,
  "Shape Rounded Rect": <AllPages.ShapeRoundedRectPage />,
  "Shape Spiral": <AllPages.ShapeSpiralPage />,
  Slow: <AllPages.SlowPage />,
  Snow: <AllPages.SnowPage />,
  "Sounds Audio": <AllPages.SoundsAudioPage />,
  "Sounds Loop": <AllPages.SoundsLoopPage />,
  "Sounds Melodies": <AllPages.SoundsMelodiesPage />,
  "Sounds Melody Loop": <AllPages.SoundsMelodyLoopPage />,
  "Sounds Notes": <AllPages.SoundsNotesPage />,
  "Speed Decay": <AllPages.SpeedDecayPage />,
  Spin: <AllPages.SpinPage />,
  Star: <AllPages.StarPage />,
  "Stroke Animation": <AllPages.StrokeAnimationPage />,
  Style: <AllPages.StylePage />,
  "Svg Replace": <AllPages.SvgReplacePage />,
  Test: <AllPages.TestPage />,
  "Text Mask": <AllPages.TextMaskPage />,
  "Text Mask Multiline": <AllPages.TextMaskMultilinePage />,
  Themes: <AllPages.ThemesPage />,
  Tilt: <AllPages.TiltPage />,
  Trail: <AllPages.TrailPage />,
  "Trail Image": <AllPages.TrailImagePage />,
  Triangles: <AllPages.TrianglesPage />,
  Twinkle: <AllPages.TwinklePage />,
  Vibrate: <AllPages.VibratePage />,
  Virus: <AllPages.VirusPage />,
  Warp: <AllPages.WarpPage />,
  Wobble: <AllPages.WobblePage />,
  "Z Index": <AllPages.ZIndexPage />,
};
